name: SQLAlchemy compat test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "5.7"
          user: scott
          password: tiger
          my-cnf: |
            innodb_log_file_size=256MB
            innodb_buffer_pool_size=512MB
            max_allowed_packet=16MB
            max_connections=50
            local_infile=1

      - name: Create database
        run: |
          mysql -h127.0.0.1 -uscott -ptiger -e "CREATE DATABASE test_schema CHARSET utf8mb4;"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install mysqlclient
        env:
          PIP_NO_PYTHON_VERSION_WARNING: 1
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev
          pip install -U pytest pytest-cov
          #python setup.py develop
          pip install -v mysqlclient  # Use stable version
          python -VV
          python -c 'import MySQLdb'

      - name: Run SQLAlchemy test
        run: |
          wget https://files.pythonhosted.org/packages/f6/d6/fcf14b752daba13a02a6669eccb025bf3ba3f814741cd23253c180a12fff/SQLAlchemy-1.4.35.tar.gz
          tar xf SQLAlchemy-1.4.35.tar.gz
          cd SQLAlchemy-1.4.35
          pip install .
          pytest --dburi=mysql://scott:tiger@127.0.0.1:3306/test_schema?charset=utf8mb4 test/
