name: SQLAlchemy compat test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "5.7"
          user: scott
          password: tiger
          my-cnf: |
            innodb_log_file_size=256MB
            innodb_buffer_pool_size=512MB
            max_allowed_packet=16MB
            max_connections=50
            local_infile=1

      - name: Create database
        run: |
          mysql -h127.0.0.1 -uscott -ptiger -e "CREATE DATABASE test_schema CHARSET utf8mb4;"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-sqla-pip-1
          restore-keys: |
            ${{ runner.os }}-sqla-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install mysqlclient
        env:
          PIP_NO_PYTHON_VERSION_WARNING: 1
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev
          pip install -U pytest pytest-cov
          #python setup.py develop
          pip install mysqlclient  # Use stable version

      - name: Run SQLAlchemy test
        run: |
          wget https://files.pythonhosted.org/packages/69/2b/f0ee898c3270d965300ec30b0bf06e062c4cc92f35d17ae6046f429c5067/SQLAlchemy-1.4.25.tar.gz
          tar xf SQLAlchemy-1.4.25.tar.gz
          cd SQLAlchemy-1.4.25
          pip install .
          pytest --dburi=mysql://scott:tiger@127.0.0.1:3306/test_schema?charset=utf8mb4 test/
